title: Ural-PDC
description: Ural Workshop on Parallel, Distributed, and Cloud Computing for Young Scientists.
email: avs@imm.uran.ru
baseurl: '/ural-pdc'
url: http://ural-pdc.org
markdown: kramdown
exclude:
- Gemfile*
- README.md
- LICENSE.txt
safe: true
timezone: Asia/Yekaterinburg
encoding: UTF-8
recent: '2016'
